name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight
  workflow_dispatch: # Allow manual triggers

jobs:
  dependabot-automation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check for dependency updates
      uses: dependabot/dependabot-core@v3
      with:
        package-manager: npm
        target-branch: main
        labels: dependencies
        versioning-strategy: auto
    
    - name: Auto-merge minor updates
      uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        target: minor
        github-token: ${{ secrets.GH_TOKEN }}
