name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight
  workflow_dispatch: # Allow manual triggers

jobs:
  dependabot-automation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Check for outdated dependencies
      run: npm outdated || true

    - name: Setup Python for Dependabot
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependabot CLI
      run: pip install dependabot-cli

    - name: Run Dependabot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dependabot check
